[package]
name = "minecraft_discord_alerts"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-mc-status = "2.0.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
